### ISSUE TITLE
Allow export of models

### ISSUE THREAD

**Issue by garrynewman** [Facepunch/RustWorkshop#1]
Some artists would like the model to be able to decorate.

**Comment by DevinWatson** [comment]
I tried making some small wooden box skins but the way the texture is mapped to the model makes it super tedious. Having the actual model to paint on would be super helpful.

**Comment by Subza** [comment]
Yeah this would be really good, easier to do then going through the rust sdk for the models (+it would have all the newer stuff that's not on the sdk).

**Comment by garrynewman** [comment]
Should have this option once the update hits Steam
