### ISSUE TITLE
Wood Storage Box Not Tagging Properly

### ISSUE THREAD

**Issue by DevinWatson** [Facepunch/RustWorkshop#10]
Published a wood storage box and it was not tagged properly.

No tags:

http://i.imgur.com/EH1RMfj.png

Tags on someone else's upload from several days ago:

http://i.imgur.com/u4SSyXO.png

I have since deleted my item and will re-publish when tags are working again.

**Comment by garrynewman** [comment]
I know what this is, on it.

**Comment by DevinWatson** [comment]
Seems to be working now.
