### ISSUE TITLE
Stone and Revolver "Null Item" Issue

### ISSUE THREAD

**Issue by StabbyMcStabface** [Facepunch/RustWorkshop#110]
I sent Garry a message about this on Twitter, but I'm sure he's deluged with messages daily so it's probably best to post it here. Currently the Revolver and Stone items on the Workshop aren't editable. You get a "Null Item" error message upon loading the image of the "vanilla" item, and replacing the individual files doesn't change the appearance. For kicks I tried to export the items and it results in the export hanging and forcing you to alt-tab-delete out of the game. Not sure if it's related to the previous skin issue or not, but revolver/stone makers be advised. lol

**Comment by garrynewman** [comment]
This should be fixed in the next update
