### ISSUE TITLE
Satchel Charge not in the lists, can't preview the existing one's either

### ISSUE THREAD

**Issue by AWDKamikaze** [Facepunch/RustWorkshop#119]
I can see that people have made a few skins for the Satchel Charge, but the model isn't in either the build list or search list. Also, when I click a user created skin that has already been made, nothing happens. It won't open it. I updated Steam and Rust and restarted steam entirely, same issue.

**Comment by raycohaex** [comment]
Go to Library > right click on Rust > click properties > click on beta's (4th option) > select "Staging-Debug" > wait for rust to update.

You will find the skin right there, If that worked. Then you should close this Issiue
