### ISSUE TITLE
long sleeves items don't show the torso nor the arms 

### ISSUE THREAD

**Issue by elfideorubio** [Facepunch/RustWorkshop#12]
Maybe this works as intended for performance, but I just wanted to make sure since I want to work with transparencies.

**Comment by Subza** [comment]
"Unfortunately, this is the way this has to work right now, since if we enable the torso underneath it will pop through the shirt. I can't think of a good way to avoid this." Garry.

This was for the Tshirt, but I'm sure it applies for long sleeve stuff to.

**Comment by garrynewman** [comment]
Yep - this is a limitation you need to work around right now, sorry :(
