### ISSUE TITLE
Can't update skin

### ISSUE THREAD

**Issue by RavvickHipnot** [Facepunch/RustWorkshop#120]
I'm trying to update a (non-accepted) burlap headwrap skin but having problems.

Everything seems fine until I publish the updated version. None of the changes appear, and the thumbnail is showing a standard burlap headwrap.

**Comment by RavvickHipnot** [comment]
Update to this. The actual changes now seem to be showing on the skin, but the thunbnail is stilll showing as the default.

**Comment by Kamiling** [comment]
The thumbnail won't update... if the skins update properly, you should see "Version 3"

**Comment by RavvickHipnot** [comment]
Forgot to update this to say that it appears to be all fixed now.
