### ISSUE TITLE
Bolt Action Rifle thumbnail

### ISSUE THREAD

**Issue by RavvickHipnot** [Facepunch/RustWorkshop#121]
I uploaded a boltie skin earlier today. The thumbnail shows the rifle pointing upwards, with the muzzle end of the barrel cropped out of the image. It doesn't look intentional.

**Comment by garrynewman** [comment]
Working okay here - have you tried with the latest version?

**Comment by RavvickHipnot** [comment]
That seems to be okay now, thanks.
