### ISSUE TITLE
Can't export mesh from the game

### ISSUE THREAD

**Issue by Mokryi** [Facepunch/RustWorkshop#122]
Hello today I tried export simple from the game (TShirt) But it doesn't work, file does not appear in the folder where I saved it. Try someone else, export the T-shirt, on your disk. And leave your comment here thx !

**Comment by zufick** [comment]
+1

**Comment by TheMarex86** [comment]
+1 Tshirt broken, tried few others they work

**Comment by garrynewman** [comment]
Fixed tshirt
