### ISSUE TITLE
Workshop broken

### ISSUE THREAD

**Issue by TheMarex86** [Facepunch/RustWorkshop#123]
Workshop is broken on normal build and staging, prerelease once workshop is opened crash game.
all skins exept last one are marked with red, and also the latest one which is not marked with red doesnt work.
Opening skins from other people doesnt work also 

![screenshot_7](https://cloud.githubusercontent.com/assets/13373211/22596000/ff5fa522-ea29-11e6-8134-a508af0be7ff.png)
![screenshot_8](https://cloud.githubusercontent.com/assets/13373211/22596001/ff620876-ea29-11e6-96cb-33b439fbe70a.png)
![screenshot_9](https://cloud.githubusercontent.com/assets/13373211/22595999/ff5f3e20-ea29-11e6-9595-272f88f164ca.png)

worked fine yesterday before update...
![s5](https://cloud.githubusercontent.com/assets/13373211/22596208/e89ac33e-ea2a-11e6-9e7a-68d577247f4b.png)

**Comment by garrynewman** [comment]
Found this bug, thanks, should be fixed on staging in about an hour, and on main some time today
