### ISSUE TITLE
Bolt texture resolution is really low

### ISSUE THREAD

**Issue by MilhoFrito** [Facepunch/RustWorkshop#139]
Hey Garry,

Can we have the possibility to upload 2048x1024 textures on the bolt? It seems 1024x512 is really low, mainly on higher resolution screens.

I want to upload this skin, but look how resolution makes it different. Also it is not using the LOD0 version when looking in 3rd person.

![bfc0ac51081f9e6b895d3d15fd54239e](https://cloud.githubusercontent.com/assets/23514225/22950970/5f58460e-f2ff-11e6-81f0-bc4be195cc18.jpg)
![9c6dc9d6f0525fdd309dd772ca1c3d80](https://cloud.githubusercontent.com/assets/23514225/22950971/606615ee-f2ff-11e6-8d77-c82606468328.png)

Thanks!

**Comment by StabbyMcStabface** [comment]
I think I'm having the same issue. In Substance Painter I'm working at 2048x1024 and it looks dynamite in renders but in game it's kind of smudgy. Then again, if all of us were walking around with 2 or 4K skins that'd be a performance hit and a half, no?
![northenerposter](https://cloud.githubusercontent.com/assets/24607834/22988524/6b5d3af0-f380-11e6-8eeb-2345516e47b2.png)
![northener5](https://cloud.githubusercontent.com/assets/24607834/22988529/70e013da-f380-11e6-992d-8ac401293552.png)

**Comment by SparkleMade** [comment]
It seems like a problem stemming from the way the whole skinning process unfolded.  I am guessing, but somewhere along the way complex items got split up into multiple pieces to help resolutions of unique areas.

custom SMG, AK, semi auto... multiple pieces to the files help with resolution of grip, stock, body, barrel... On earlier released items like thompson and bolt you have the UV all in one, forcing resolution issues as some items are scaled down on the UV MAP.

**Comment by MilhoFrito** [comment]
The problem is that some bolt skins were already accepted, so making a new mesh maybe isn't the best idea.
My suggestion is to raise the resolution to 2048x1024

**Comment by garrynewman** [comment]
Done

**Comment by MilhoFrito** [comment]
That was fast! Thanks Garry! 

But can we also have the LOD0 model in 3rd person? I want to take some screenshots but it looks so bad because it stretches the texture.
