### ISSUE TITLE
Specular vs Metallicity

### ISSUE THREAD

**Issue by DevinWatson** [Facepunch/RustWorkshop#14]
I'm playing around with trying to make some very metallic textures unfortunately the results are pretty awful. 

Here is what I was going for:

![CopperTest](http://i.imgur.com/AMzucYs.png)

Here is the best I can manage in game:

![CopperTestInGame](http://i.imgur.com/I7zxDgU.jpg)

Here is the exported textures from SP2:

[Facemask.zip](https://github.com/Facepunch/RustWorkshop/files/557507/Facemask.zip)

I'm assuming it's an issue with having a specular material vs a metallic material; or maybe just not having access to configure all the options on the Unity material; or maybe I just suck.

Full disclosure I have no idea what I'm doing.

**Comment by Subza** [comment]
I also have this issue. When it comes to making something glossy/wet looking it works fine, but metallic things come out just looking glossy.

When we used unity to publish stuff i would just export a metallic channel and use that, now I'm not to sure what to do.

I only have one skin with metal parts on it so it's not that bad. 
![784935429_preview_22](https://cloud.githubusercontent.com/assets/13123653/19798954/a19fa946-9d3f-11e6-9a96-d87d05e26ba8.jpg)

The best i could do was create my own specular with everything transparent except the metal stitches and set it to white, i tried a lot of things and this gave the best result, but yeah I'm also in the boat of no idea what I'm doing.

**Comment by garrynewman** [comment]
I'll look into this, but one thing to keep in mind is that this is what they look like in game. We don't have great reflections in game, so this is why they look so different to how they did in the editor sdk environment.

**Comment by DevinWatson** [comment]
The specular color options have let me get the results I want:

![Gooooooold](http://i.imgur.com/a79tj2q.jpg)

Thanks!
