### ISSUE TITLE
Are fridge doors for writing on?

### ISSUE THREAD

**Issue by RavvickHipnot** [Facepunch/RustWorkshop#143]
I noticed that the Rust Updates Twitter account posted "fridge door tweaks for readability". Does that mean that part of the fridge can be written on like a sign?

Would be good to know in case there's a bit that we shouldn't be getting rid of when we're making new skins for it. Or maybe I'm making 2+2=Writable Area On Fridge.

**Comment by garrynewman** [comment]
no
