### ISSUE TITLE
3. person ak model broken?

### ISSUE THREAD

**Issue by madroce** [Facepunch/RustWorkshop#147]
http://i.epvpimg.com/tJOXbab.jpg

i noticed today that the 3rd person model of the ak seems to be weird. After looking in the workshop it seems like every newly uploaded ak skin has the same problem so its not just me.

**Comment by SparkleMade** [comment]
no madroce, its you... we all know you're truly just fucked up

xxoo (kisses and hugs)

lol I just saw the stick figure in his bellybutton

**Comment by SparkleMade** [comment]
On a serious note, guns submitted on the 9th are showing gastube nuts, trigger, trigger guard, and stock screw, guns submitted on the 10th are missing the items.

Just to wrap up madroce and his antics, regarding his stick figures.... 

Mr.Sparkle: i looked at his shoulder and Im like... is that  a stick figure? then his ear and nose
Mr.Sparkle: then i see the guy off in the distance on the right
Mr.Sparkle: and lastly caught the one in the belly button after I started looking for them
Mr.Sparkle: and that made me laugh out lout literally
Mr.Sparkle: lol
madroce: lel
madroce: honestly took more time to make them than making that ak
Mr.Sparkle: lol

**Comment by madroce** [comment]
regarding that the 10th of february was a friday means that it probably has something to do with the update on thursday the day before :/

edit: just checked ak on staging debug and the vanilla ak is there also broken :(

**Comment by SparkleMade** [comment]
Just thinking randomly I remembered at a while back on store I saw the alien red ak on the missing the same things, now I realize its related to this issue.  checked the store and agony yellow ak is the same.

**Comment by RavvickHipnot** [comment]
I posted this issue a couple of weeks ago. Apparently it's the world model we're seeing instead of the viewmodel. If you click the button to view your skin from the player's perspective, you get to see the "proper" model. Admittedly you don't see a lot of it!

**Comment by madroce** [comment]
ah its fixed thnak you facepunch
