### ISSUE TITLE
Spinner Wheel

### ISSUE THREAD

**Issue by Kamiling** [Facepunch/RustWorkshop#160]
I just try to edit texture of the Spinning Wheel but doesn't work. Only can be edited the metal parts

**Comment by RavvickHipnot** [comment]
Same here. The main circular part doesn't seem to accept new textures.
![tweet](https://cloud.githubusercontent.com/assets/25491269/24084063/0879bfa2-0cdb-11e7-8dde-df04cc9ac31a.jpg)
...Cockface.

**Comment by Kamiling** [comment]
Fixed now
