### ISSUE TITLE
Workshop Icons will not be generated

### ISSUE THREAD

**Issue by dr-d-bug** [Facepunch/RustWorkshop#191]
Is there currently a bug in the creation of workshop items? I can edit and publish objects, but no workshop icon will be generated. It also does not appear in the Rust-Inventory, although the object works perfectly in the game. Interesting fact; not every item is affected. It seems that only clothes are affected with this issue. Here are some of the items i have tried to create.

TShirt: does not work ✘
AK47: works fine ✔
Armored Door: works fine ✔
Armored Double Door: works fine ✔
Bandana: does not work ✘
Beenie Hat: does not work ✘
Bolt-Rifle: works fine ✔
Bone Club: works fine ✔
Bone Knife: works fine ✔
Bucket Helmet: does not work ✘
Burlap Headwrap: does not work ✘

![missing_icon_workshop](https://user-images.githubusercontent.com/49510052/75035630-3944aa00-54b0-11ea-8535-f54a5814c66e.png)

**Comment by Bluesuffer** [comment]
I have the same issue, but in-game! kind of frustrating....

As you can se on the picture, all areas are blank, but when in fact the 5 first are actually a hoodie, pants, and a full set of roadsign armor.. Seems like the only items affected are the ones in Attire!
`<script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>`

**Comment by Bluesuffer** [comment]
Same problem here, only it's affecting in-game skins. And it's frustrating when running spawngear on a server when the merch can't show!! as you look at the picture with this, the fields are blanc, when they however are not!

I managed to lure in a backround icon file when uploading it, through temp files.. but gosh darnit, it's not supposed to work like that! pleeeeeease fix this!!

[click HERE to see picture](https://i.imgur.com/EIWaJli.jpg)
<img>https://i.imgur.com/EIWaJli.jpg</img>

**Comment by dr-d-bug** [comment]
issue is already fixed.
