### ISSUE TITLE
Everything Rendering Transparent In Workshop

### ISSUE THREAD

**Issue by DevinWatson** [Facepunch/RustWorkshop#2]
On pre-release the workshop level / scene is rendering transparent:

[http://i.imgur.com/cnMVtTX.jpg](http://i.imgur.com/cnMVtTX.jpg)

[DxDiag](https://gist.github.com/DevinWatson/17b4bce1f9a4745144e20977379f4c00)

**Comment by DevinWatson** [comment]
Currently using [this ](https://steamdb.info/app/252490/history/?changeid=2366681) version to render screenshots, and the current version to push to Steam.

**Comment by garrynewman** [comment]
Does the linked version render properly in game?

Can you try doing

revz 0

in the console, to see if it makes any difference

**Comment by DevinWatson** [comment]
The linked older version works properly. Running revz 0 does fix the issue on the current version of pre-release.

[http://i.imgur.com/wIYUsmi.jpg](http://i.imgur.com/wIYUsmi.jpg)

**Comment by garrynewman** [comment]
Thanks - found the repro, working on this now
