### ISSUE TITLE
Bones knife diffuse is transparent

### ISSUE THREAD

**Issue by Subza** [Facepunch/RustWorkshop#26]
Could be intended but the bone knife diffuse is currently extremely transparent making it a bit harder to work on.
![test2](https://cloud.githubusercontent.com/assets/13123653/19869695/834247b4-a001-11e6-9a26-e33eabbef71f.png)

Also the icon for the bone knife is really bright.
![icon_background](https://cloud.githubusercontent.com/assets/13123653/19869748/bcf17e76-a001-11e6-8da1-44f09b6add24.png)

**Comment by DevinWatson** [comment]
There are a number of items that have transparent diffuse textures (ie. bolt rifle, wooden storage box, burlap shoes, etc..) and it makes them rather difficult to work with. Would be great if we could get textures with no alpha for the diffuse layer.

**Comment by garrynewman** [comment]
This is left over from when Unity used the alpha as specular or something. I'll fix the ones mentioned - if there's others let me know in another ticket.
