### ISSUE TITLE
Emission Mask Not Working?

### ISSUE THREAD

**Issue by DevinWatson** [Facepunch/RustWorkshop#27]
Tried playing around with the new emissions options and can't seem to get the emission mask working. Is the mask a black & white mask, gray scale, or do I need alpha channels? Everything I've tried still affects the emissivity of the entire model.

**Comment by garrynewman** [comment]
Just committed a fix for this - let me know if it works/doesn't work

**Comment by DevinWatson** [comment]
Still not working for me, see the attached textures for the metal face mask.

[Emissions_Test.zip](https://github.com/Facepunch/RustWorkshop/files/566572/Emissions_Test.zip)

**Comment by garrynewman** [comment]
Should be good now once the update hits

**Comment by DevinWatson** [comment]
Fixed
