### ISSUE TITLE
Skin icons problem

### ISSUE THREAD

**Issue by Kamiling** [Facepunch/RustWorkshop#28]
Everytime when I upload a Facemask skin, the icon looks like this.
![descarga](https://cloud.githubusercontent.com/assets/23229044/19955969/9cdb3072-a165-11e6-9fad-ea0832dbf3d4.jpg)

**Comment by Kamiling** [comment]
Every icon look like that.
![descarga](https://cloud.githubusercontent.com/assets/23229044/19956083/ec4e467a-a166-11e6-84ce-18c1cd4a58d0.jpg)

**Comment by Subza** [comment]
Worked fine for me.
![previewfile_792500397](https://cloud.githubusercontent.com/assets/13123653/19956222/0c3d9d92-a1de-11e6-91a8-8c82f101e205.png)

Perhaps its something to do with your game settings? I know if you play on low settings your preview icon will come out looking pretty bad. Only thing i can think of sorry.

**Comment by Kamiling** [comment]
I use the game with all in max. I try verify cache, reinstalling rust, trying with other maps, and still the same.

I have over 350 skins published on workshop... and i never had this problem.

**Comment by garrynewman** [comment]
What OS are you on? Do you have any command lines set?

**Comment by Kamiling** [comment]
I use Windows 7 64bits, and no... no command lines set.

Now i guess it works, but steam if a little fucked right now.

**Comment by Kamiling** [comment]
Ok... isn't fixed. The icon look like this
![descarga](https://cloud.githubusercontent.com/assets/23229044/19978472/d4621806-a1d5-11e6-9248-7c438393a33c.jpg)

And this is the skin
![3](https://cloud.githubusercontent.com/assets/23229044/19978483/df18f26a-a1d5-11e6-949d-b765752fecf0.jpg)

**Comment by Subza** [comment]
It looks like somethings going on with the outline that gets created. I've noticed a few skins in the workshop with the same or similar problems.
![previewfile_792640380](https://cloud.githubusercontent.com/assets/13123653/19978912/a98ba166-a24c-11e6-83e6-eb9e5366da02.png)

**Comment by Kamiling** [comment]
Yeah... I figure that, i have a similar problem with another skins the last days... but not too big.
![descarga](https://cloud.githubusercontent.com/assets/23229044/19979078/e0127d06-a1d7-11e6-9058-6cf568785932.jpg)

**Comment by Kamiling** [comment]
No fix yet?

**Comment by v1be** [comment]
![download 6](https://cloud.githubusercontent.com/assets/23247686/19986693/9a571870-a20f-11e6-8cf0-4d00793ef401.jpg)

Also having this issue

**Comment by Kamiling** [comment]
AMD?

**Comment by v1be** [comment]
Yes, 7950

**Comment by Kamiling** [comment]
Fred The Dog have amd too.. he touch the FOV and this happens to him.

Maybe is a strange problem with amd, people hate us.

**Comment by v1be** [comment]
Interesting that you mention the fov, I've been tweaking almost every other setting trying to find what's causing it. Perhaps that is a solid lead as to what's causing the issue. 

Have you tried reducing fov to the minimum, restarting the game and then trying to publish an item?

Edit: I tried it, no change. Probably just a coincidence that he changed it right around the time the issue started occurring.

**Comment by Kamiling** [comment]
I try with every one fov level, from minimum to max.
I verify cache, reinstall the game, i go to prerelease debug, reboot my pc, touch the resolutions, fullscreen, windowed, i open on lowest, good and fantastic, I try use all the map on each skins, etc, nothing works.

**Comment by v1be** [comment]
might be a conflict with AMD then after one of the Rust updates, since I haven't touched my drivers at all. I'll try updating to the latest AMD drivers now.

**Comment by Kamiling** [comment]
Is strange, i upload 350 skins without this problem... and this start happening yesterday.

i have all the drivers update too.

**Comment by WILDCAT32** [comment]
I have this problem too, gpu amd radeon 6900 hd series. :((
Win7 x64
#Garryhelpus

**Comment by garrynewman** [comment]
I'm gonna rewrite how the outline is drawn over the weekend. That should fix this.

**Comment by Kamiling** [comment]
Thanks Garry. We still love u

**Comment by leosapucaia** [comment]
Same here... :'
![icon_background](https://cloud.githubusercontent.com/assets/2192794/20033897/0bf9181c-a38b-11e6-8b01-9434acc876e0.png)

**Comment by garrynewman** [comment]
Submitted an update to Steam. If you're having this problem jump on the staging branch and let me know if it's still happening.

**Comment by v1be** [comment]
Still having the issue on staging.

**Comment by CrazySerge** [comment]
This same problem I have. How to deal with it?

![previewfile_794569507](https://cloud.githubusercontent.com/assets/23292875/20037714/dbbfbf3c-a436-11e6-84b2-b39fcd1c3c19.png)

**Comment by v1be** [comment]
![xaal4kf](https://cloud.githubusercontent.com/assets/23247686/20037837/33aab33a-a420-11e6-912e-02bbafced25d.jpg)

Works, but the angle is different from before

This was after the 101.8mb update

another icon test

![download](https://cloud.githubusercontent.com/assets/23247686/20037840/3e940620-a420-11e6-9f27-fd8fe8b34e13.jpg)

**Comment by garrynewman** [comment]
Just committed another one that should fix that - should be live in 10 mins - sorry !

**Comment by leosapucaia** [comment]
Works! It's alive! :)
![icon_background](https://cloud.githubusercontent.com/assets/2192794/20038100/665502e0-a40c-11e6-8cbf-433aec903a62.png)

**Comment by v1be** [comment]
No complaints here Garry, thank you very much for fixing it! :)

**Comment by WILDCAT32** [comment]
Thank you so much Garry
![icon_background](https://cloud.githubusercontent.com/assets/23267838/20038879/126bc318-a44c-11e6-88aa-e5464abd02b8.png)

**Comment by CrazySerge** [comment]
All the same, there was a problem. How to be? Upgrading just downloaded, all the same, nothing has changed.

**Comment by MickDodge** [comment]
I just created a skin. This is still happening. I cant see the fill image. People are uploading the same at the moment it you look at new submissions :(  Please fix this! I want to unleash me artist within! :)

**Comment by v1be** [comment]
@MickDodge have you switched to staging branch via Rust steam properties? I am able to upload now. Check Garry's post above. 

If anyone is having trouble finding the staging branch, right click Rust in the Steam library, go to Properties and then the 'Betas' menu. In the first drop down menu select 'staging', and let your game update.

**Comment by MickDodge** [comment]
Thanks I will give it a try!

**Comment by Kamiling** [comment]
Solved now...
