### ISSUE TITLE
T-Shirt Transparency Not Functioning Correctly

### ISSUE THREAD

**Issue by DevinWatson** [Facepunch/RustWorkshop#3]
T-Shirt transparency is not functioning correctly:
[http://i.imgur.com/9JbMlYt.jpg](http://i.imgur.com/9JbMlYt.jpg)

**Comment by garrynewman** [comment]
Unfortunately, this is the way this has to work right now, since if we enable the torso underneath it will pop through the shirt. I can't think of a good way to avoid this.

**Comment by DevinWatson** [comment]
Closing, no easy fix.

**Comment by Subza** [comment]
Was about to report this myself as it makes my new highly fashionable T-shirt not look that great.

![3](https://cloud.githubusercontent.com/assets/13123653/19623322/0ce0c79a-9911-11e6-996c-867555d5e325.jpg)

O well, too bad there isn't a easy fix.
