### ISSUE TITLE
Workshop Upload Problems

### ISSUE THREAD

**Issue by Bibo164** [Facepunch/RustWorkshop#30]
I've created 3 different skins for Rust in Unity
I'm trying to upload these since half a year... I checked the meta.asset file multiple times but it always just creates an emtpy workshop page, size of skin is 0.000MB, no desc and no image.
I used the time to improve the skins - they're pretty decent now and I finally want to publish them.
Any help? Please!

Thank you in advance!

**Comment by Kamiling** [comment]
Now u need upload the skins from RUST. Rustsdk on unity don't work anymore

**Comment by Bibo164** [comment]
Thank you! I can't believe I didn't get that...
But another problem: I can't see the skin type for the semi auto pistol there. Is this just me or can't you publish any more gun skins?
