### ISSUE TITLE
Export Button

### ISSUE THREAD

**Issue by Kamiling** [Facepunch/RustWorkshop#31]
The export button works on other people skins in rust. This is Intentionally?

**Comment by chaingang132** [comment]
It's not cool, I can download other peoples textures and publish them as my own. Hope you guys remove the option pretty fast

**Comment by garrynewman** [comment]
Yeah it's intentional. We can all learn from each other.

We could get rid of the export feature - but you can download anything and view its contents anyway. So why try to hide it?
