### ISSUE TITLE
Emission Color effects entire model regardless of mask

### ISSUE THREAD

**Issue by kfhammond** [Facepunch/RustWorkshop#32]
Entire model becomes emissive when using the emission color slider, even when an appropriate mask is connected. Experiencing the problem both on the release version and prerelease. Emission masks were working just fine for me as of [November 3](http://steamcommunity.com/sharedfiles/filedetails/?id=785847792)

**Comment by garrynewman** [comment]
Which model?

**Comment by kfhammond** [comment]
error occurs on:
bandana, boltrifle, burlap headwrap, burlap shirt, hide halterneck, hide pants, hide shirt, hide shoes, hide skirt, large woodbox, sandbag barricade, sleeping bag. 

works fine on all other items.

**Comment by garrynewman** [comment]
Do you have your shader level turned down in settings?

**Comment by kfhammond** [comment]
shader level is currently maxed at 600

**Comment by garrynewman** [comment]
I can't recreate this, sorry

**Comment by kfhammond** [comment]
Dang! I know of some other contributors having the same problem. Oh well, we'll figure it out! Thanks Garry. :)

**Comment by Nikolaj1310** [comment]
It seems it doesn't work for the Armored door or the Sheetmetal Door as well...
