### ISSUE TITLE
Transparency / Alpha Not Working On Pants

### ISSUE THREAD

**Issue by DevinWatson** [Facepunch/RustWorkshop#4]
Transparency / alpha is not working on the pants model. Imported same texture onto tank top model and transparency worked fine.

[http://i.imgur.com/7WnzTbk.jpg](http://i.imgur.com/7WnzTbk.jpg)

**Comment by garrynewman** [comment]
Confirmed

**Comment by garrynewman** [comment]
This should be working now - confirm?

**Comment by DevinWatson** [comment]
Can confirm is working now.
