### ISSUE TITLE
Disable LODs

### ISSUE THREAD

**Issue by kfhammond** [Facepunch/RustWorkshop#42]
Some items show lower quality LODs while taking screenshots. Generated thumbnails don't seam to be using LOD 0 either.

**Comment by garrynewman** [comment]
Can you name a few of the items for me?

**Comment by kfhammond** [comment]
I noticed it on the semi-auto pistol. It seams to be missing the little spring on the bottom? is that an LOD issue, or is the a world model/view model thing?

**Comment by garrynewman** [comment]
Should be good in the next update

**Comment by kfhammond** [comment]
Thanks Garry! :)
