### ISSUE TITLE
Emission not working on armored doors 

### ISSUE THREAD

**Issue by elfideorubio** [Facepunch/RustWorkshop#46]
https://gyazo.com/d86e6ecf628c8047c4eaa04ac8b761bf
https://gyazo.com/d705c0563694bcbc05a3e52baea68525

**Comment by bokatau** [comment]
+1

**Comment by Kamiling** [comment]
+1

**Comment by kfhammond** [comment]
Just out of curiosity, are you guys experiencing the same problem with the following items:

bandana, boltrifle, burlap headwrap, burlap shirt, hide halterneck, hide pants, hide shirt, hide shoes, hide skirt, large woodbox, sandbag barricade, sleeping bag

or any other items?

**Comment by Nikolaj1310** [comment]
Neither does it work for Sheetmetal doors...

**Comment by elfideorubio** [comment]
guys it's fixed yeahhh, thanks garry. 

![20161117222700_1](https://cloud.githubusercontent.com/assets/23042715/20582275/01a302c0-b1e0-11e6-86f6-0e0fda946c48.jpg)

![20161124004754_1](https://cloud.githubusercontent.com/assets/23042715/20582280/0bd21808-b1e0-11e6-8cc8-3d0cacdd5dd4.jpg)

**Comment by Nikolaj1310** [comment]
Are you on the staging branch or not? Because it worked for me on staging yesterday noon
