### ISSUE TITLE
Error opening V2 skins

### ISSUE THREAD

**Issue by MilhoFrito** [Facepunch/RustWorkshop#47]
Hey, as you asked I opened a new issue for this.
This is the error I'm having when opening V2 skins. I'm already using staging branch.

<a href="https://gyazo.com/c9b7eb5c61877f143efaa8a35486b639"><img src="https://i.gyazo.com/c9b7eb5c61877f143efaa8a35486b639.png" alt="https://gyazo.com/c9b7eb5c61877f143efaa8a35486b639" width="509"/></a>

Thanks,
Milho Frito

**Comment by garrynewman** [comment]
Just committed a fix for this, but it's building. Give it a try on the staging branch in an hour and let me know if it's fixes or not here.

**Comment by MilhoFrito** [comment]
All those erros disappeared but still having the "asset == null" and the textures won't show up

<a href="https://gyazo.com/ab36888090afd712bd7ee223c7bea786"><img src="https://i.gyazo.com/ab36888090afd712bd7ee223c7bea786.jpg" alt="https://gyazo.com/ab36888090afd712bd7ee223c7bea786" width="2025"/></a>

**Comment by garrynewman** [comment]
What's your SteamId, I'll make it think I'm you and make it work.

**Comment by MilhoFrito** [comment]
Hey, there it is: STEAM_0:1:11796605

**Comment by garrynewman** [comment]
Okay this should be all fixed now - available on the staging branch in about an hour

**Comment by MilhoFrito** [comment]
Thanks a lot Garry! It's working now!

**Comment by MilhoFrito** [comment]
I tried to update this one and it seemed like everything went well. But it still says Version 2.

<a href="https://gyazo.com/a6140a656d475d7dd1830b96b783c1d9"><img src="https://i.gyazo.com/a6140a656d475d7dd1830b96b783c1d9.png" alt="https://gyazo.com/a6140a656d475d7dd1830b96b783c1d9" width="285"/></a>

**Comment by MilhoFrito** [comment]
Hey Garry, I waited for some updates to see if this was fixed, but no lucky. It uploads, but it's not updating to V3.

I would like to know if votes are really decisive, because if think it's better to upload the V2 as new ones manually, and losing all the votes/views.

What should I do?
Thanks

**Comment by garrynewman** [comment]
Did it not update the thumb and the tags - is that right?

**Comment by MilhoFrito** [comment]
Right, but i'm already uploading them as new ones. So it's ok ;)
Thanks

**Comment by garrynewman** [comment]
Huh?

**Comment by MilhoFrito** [comment]
Sorry, maybe I didn't explain it well.

When I open my V2 skins in order to update them to V3, it doesn't update. It says "uploading" and then the skin page opens, but it says Version 2.

But it doesn't matter. I already started uploading them manually as new ones.

Thanks for your time

**Comment by garrynewman** [comment]
It's not the first time I've heard of it happening. Can you link me to one of your skins that you've tried updating and is failing?

**Comment by MilhoFrito** [comment]
Sure.
http://steamcommunity.com/sharedfiles/filedetails/?id=696566296

**Comment by garrynewman** [comment]
Can you try to update it and see if there are any errors in the console?

**Comment by MilhoFrito** [comment]
Done, and no errors.
