### ISSUE TITLE
Wiki Tutorials

### ISSUE THREAD

**Issue by DevinWatson** [Facepunch/RustWorkshop#5]
I put together a few tutorials, unfortunately you can't make a PR on wiki's on GitHub.

[https://github.com/DevinWatson/RustWorkshop/wiki](https://github.com/DevinWatson/RustWorkshop/wiki)

**Comment by garrynewman** [comment]
I don't know how to copy these to the new wiki :/

**Comment by DevinWatson** [comment]
You can clone them locally and copy the files over.

git clone https://github.com/DevinWatson/RustWorkshop.wiki.git

Looking back these are kinda crap; might put together some better ones when the workshop stuff is more finalize.
