### ISSUE TITLE
Issue with icons using Emission 

### ISSUE THREAD

**Issue by Nikolaj1310** [Facepunch/RustWorkshop#50]
I made a skin for a Large Storage Box the emission luckily works, but when i publish it, the icon is with full emission and its hard to see what the skin is meant to be.

**Comment by Nikolaj1310** [comment]
What the icon looks like:

![icon_background](https://cloud.githubusercontent.com/assets/23654059/20556050/85f58942-b165-11e6-8560-515e4a735491.png)

**Comment by Nikolaj1310** [comment]
What the skin actually looks like:


![faft 1](https://cloud.githubusercontent.com/assets/23654059/20556090/b603d8dc-b165-11e6-9bb6-ccf8e9d8751e.PNG)

![faft 5](https://cloud.githubusercontent.com/assets/23654059/20556103/c4f364e8-b165-11e6-8872-7198da0ab683.PNG)

**Comment by garrynewman** [comment]
Interesting, I'll look into this today

**Comment by garrynewman** [comment]
Got an update coming down the line - can you try to re-publish in about an hour on the staging branch?

**Comment by Nikolaj1310** [comment]
Can i get a reference to the branch?

As i don't where to find it.

**Comment by garrynewman** [comment]
Right click Rust on Steam, properties

http://files.facepunch.com/garry/f35c/8b8a.png

**Comment by Nikolaj1310** [comment]
Oh, i get it. I thought you meant this issue, but i just realised you meant the skin, i'll publish it asap and write the result here

**Comment by Nikolaj1310** [comment]
It seems that nothing happened, the icon is still wrong

**Comment by garrynewman** [comment]
Sorry, it didn't upload  - try again now please

**Comment by Nikolaj1310** [comment]
I'm sorry to say, but that didn't work either.

**Comment by garrynewman** [comment]
Okay - got another fix in the pipeline, can you try again in an hour

**Comment by Nikolaj1310** [comment]
I've just tried it and it works perfectly fine, even the export is right :) 

Appreciate the great support! Shall i use the staging workshop from now on, or will this fix be included in the update tommorrow?
