### ISSUE TITLE
(SOLVED) Mass publishment of skins > lack of votes 

### ISSUE THREAD

**Issue by raycohaex** [Facepunch/RustWorkshop#51]
Not sure if i put it at the right place. But one of the things that is kinda annoying at this moment is the way people download a image from google (i actually check and this is true most of the times). And then put it on every commonly used item. 

Why is this anonying? Most people including me look at the recent tab, if a skin does not reach enough votes it will just disapear between the other skins that didn't make it to "populair". I'm spending alot of time on my skins and i barrely reach over 70 votes in total, my last skin a 89% possitive and doesn't get any more votes right now, (it still had under 100 votes in total). 

Yet the workshop should be accesable for everyone, and everyone should be able to post skins. But my point is that i don't really see this issiue in the csgo workshop, and people do get regulair votes.
In devlog 135 was stated "No-one else bothered to approve any skins, so I added a few"
So i think it's main issiue for multiple people. Instead of spreading hate I just hope to trigger a solution.

Yes, im also the guy who commented on the controversial topic of time ago about skins being removed. This is the main reason i was mad about it, cause it's rediculously hard to get a skin ingame by votes, you just gotta be lucky that your skin gets seen by one of the facepunch employee.

**Comment by zufick** [comment]
+1

**Comment by raycohaex** [comment]
And it used to be much much easier to gain votes, back in rustSDK. Don't take this wrong garry, you made the new workshop so much better and i do really like it!

**Comment by garrynewman** [comment]
What do you want us to do?

**Comment by raycohaex** [comment]
Maybe look into a way to either
a) get people to vote more frequent (a toggable voting list in queue screen (and not loading)
b) make the workshop less accesable like csgo (i personally dont think it will help much)???

Personally i don't really have a idea what would work out best. But not trying anything wouldn't change much. I made this post in the hope that any other workshop creator would have an idea

**Comment by fbink** [comment]
Hi all, I have long been in 3d, and I support DutchAllians

**Comment by fbink** [comment]
I support this theme in favor DutchAllians

**Comment by Mokryi** [comment]
I gonna try another game because im wasting time, because of my lack of votes on skins

**Comment by raycohaex** [comment]
My point is that stuff like this
![image](https://cloud.githubusercontent.com/assets/11200658/20563056/1333c316-b187-11e6-903b-02b438259b54.png)
Get published really fast, and if you dont reach enough votes to get in populair then you just wasted your time.

Why that skin? well it's made by downloading this google image. Only difference is that this guy only did it on one skin. I'm hoping someone could figure a way to get people to vote more frequent or well.. making it harder to submit your skin?
![image](https://cloud.githubusercontent.com/assets/11200658/20563094/493c5e1e-b187-11e6-9e4c-1fad19325c74.png)

**Comment by Mokryi** [comment]
![image](https://cloud.githubusercontent.com/assets/18554904/20563162/fc8c5782-b18f-11e6-8d29-676e3e04234d.png)
Awesome Stuff Garry 
I'm going to buy a picture from Google for $ 10

**Comment by raycohaex** [comment]
If you look at csgo workshop, alot of people have dreams of making skins, but if people actually wanna do it they have to do research how to acces their workshop and secondly how to make skins. 
This will create a controversial topic im afraid so i don't know if it's a solution

**Comment by garrynewman** [comment]
I'm not making the system harder to use just so you get more votes on your items.

**Comment by raycohaex** [comment]
I wouldn't be happy with that either. just saying that it's  a working method, but copying csgo workshop wont mean it's going to improve rust workshop. 
How about a way that people can vote skins ingame (by pressing f2 or whatever) if they are crafting something or waiting for daylight or whenever they feel like doing so if they're on idle ingame.

Again, it's just a suggestion.

**Comment by raycohaex** [comment]
> How about a way that people can vote skins ingame (by pressing f2 or whatever) <

I dont mean to litteraly let the community vote skins into rust. But i mean while they are in a server. and if they are on idle that they can vote skins if they would want to. without having to quit the server to open workshop or alt+tab open steam

**Comment by kfhammond** [comment]
I believe the csgo workshop doesn't have this problem because they have moderators that strictly enforce the rules of the workshop. Items that's that break the rules (including copyright infringement) will be marked "incompatible" and become hidden from the voting queue. What are your thoughts on a system like this for the Rust workshop Garry?

**Comment by garrynewman** [comment]
Maybe we could hire a moderator to remove all but your uploads

**Comment by Mokryi** [comment]
You do not need to delete all uploads. Just need any moderators. This error(google copy-paste) is the perfect time for it to start, look for the team moderators. Plz. 
And by the way, I've noticed a trend that most people still tight, "dislike" button, even if the work is done well.

**Comment by Subza** [comment]
The workshops gonna get spammed with the same camo pattern from google over and over, that's just the way it is.

But i do think skins that are actually good should get more recognition, right now the 3 skins in the featured thing (The ones the appear when you click on rust in the steam library) get a ridiculous amount of views compared to ones that don't make it there.

My solution would be having a spot on the main menu of rust exclusively for skins, right now its getting taken over by the dev and community blogs. Doing this should give skins in general a lot more votes, perhaps have something like 3 skins for more recent and 3 of the today's most popular?. 

If possible i think it would be best if one person couldn't have more than 1 skin on these at the same time to prevent someone spamming submissions and taking up all three spots of most recent.

![mainmenu](https://cloud.githubusercontent.com/assets/13123653/20585986/e166d8aa-b253-11e6-91ce-906b4e0f5262.jpg)

You get the idea.

**Comment by bokatau** [comment]
The workshop is now a bunch of nightmares, thank God that it is still possible to find something. I saw a man entered the "courage" and published shit 4 hour without stopping...
![222](https://cloud.githubusercontent.com/assets/23529584/20604738/fa7b572e-b278-11e6-8eef-a26e34dd1cd3.PNG)

**Comment by bokatau** [comment]
These authors not only pollute top, but also mass unlike other works, it interferes with normal work.
Entrance to the top to become completely random tape.
I do not say that my work is good, but it's pretty obvious example.

![2016-11-24 19 08 12](https://cloud.githubusercontent.com/assets/23529584/20604924/f2b6b6a4-b279-11e6-84fd-aeaf3710f714.png)

This is partly because in the small workshop traffic. Аuthors dislike authors, well, or what is paid to vote ...
The traffic is so small that the 10 votes of "friends" or "my imaginary friend" (if you understand) can be critical to getting TOP 3 or the destruction any competitors in TOP3. I saw the Turkish friends that immediately upon the publication itself took about 15-20 vote, despite the fact that such traffic would not at night. All of us on the border of what we have armies of "fictional friends" and attack each other.
We need more regular players vote. We need more regular players traffic. 


Subza suggested a good idea that people would have seen not only "advanced" work

**Comment by raycohaex** [comment]
I'm not sure if garry took inspiration from this post or not, yet he did a good thing by making the reddit post. I think most content creators just want assurance to know if their skin will be noticed or not. Khajiit what you pointed out happands in alot of workshops especially the csgo one.
[3kliksphilip](https://www.youtube.com/watch?v=fd_ria_6lHo&t=0s) made a video on it
( https://www.youtube.com/watch?v=fd_ria_6lHo&t=0s )

regardless, thank you Garry.

**Comment by bokatau** [comment]
I think they see all the "adequate" job, i do not doubt it. Guys do it well.
We can see that shit in the store is not passed, except for "Death Mask" but finally - it is sold fine.
Negative evaluations may affect the decision to add a item, even if it is liked for those who make a decision.
I'm worried because of this.

**Comment by raycohaex** [comment]
@KhajiitWORKSHOP Garry can't really change the way the community reacts I'm afraid.
