### ISSUE TITLE
Strange Water

### ISSUE THREAD

**Issue by Kamiling** [Facepunch/RustWorkshop#52]
![a](https://cloud.githubusercontent.com/assets/23229044/20568527/98270c7e-b17b-11e6-9785-75822474f246.jpg)
Sorry i post before publish this... i have this problem with water

**Comment by garrynewman** [comment]
Haven't been able to recreate this, anyone else?

**Comment by Kamiling** [comment]
Is... strange, i only have this problem on workshop. When playing everything is ok.

**Comment by bokatau** [comment]
It looks like your graphics card artifacts, never seen such.
