### ISSUE TITLE
Spam WorkShop

### ISSUE THREAD

**Issue by bokatau** [Facepunch/RustWorkshop#55]
I know ... I know ... we already talked about that in the workshop many bad works, but right now there is someone has started spamming (with dummy accounts)

![2016-11-28 00 42 28](https://cloud.githubusercontent.com/assets/23529584/20652081/ecfc6150-b503-11e6-91b8-029f9ad09f48.png)

![2016-11-28 00 45 35](https://cloud.githubusercontent.com/assets/23529584/20652086/01e2ec1a-b504-11e6-981b-888944e02dec.png)

![2016-11-28 00 45 41](https://cloud.githubusercontent.com/assets/23529584/20652087/01e5921c-b504-11e6-9c3d-26579a8343bd.png)

![2016-11-28 00 46 20](https://cloud.githubusercontent.com/assets/23529584/20652092/17f01492-b504-11e6-90d6-5122a51c089c.png)

Make something with it as possible.

**Comment by garrynewman** [comment]
What makes you think these are done by dummy accounts?

**Comment by bokatau** [comment]
His nickname was something like "sghdsfh"
I cant find it works now, you probably deleted it. Thank you.

**Comment by bokatau** [comment]
If you take the moderator, would do well to introduce basic rules like:

1. Do not change radically the original subject material (Metal door of stone)
2. Do not use a uniform surface texture at all ...

Thank you very much that it is possible to talk with you here so directly, it's very nice that you watch the community, I understand that you have a lot to do and it can be difficult for you.
