### ISSUE TITLE
Issue trying to update AK from V1 to V3

### ISSUE THREAD

**Issue by Kamiling** [Facepunch/RustWorkshop#56]
When we try to update a V1 skin to V3, we need convert the tga to png, but there's a export problem with the ak.

Only download one file.

**Comment by Kamiling** [comment]
And with V2 AK skins the magazine file is on the body tab, and viceversa.

**Comment by garrynewman** [comment]
Can you explain the problem a bit better

**Comment by Kamiling** [comment]
When AK was added to workshop a long time ago, only use one file. So... we can't update that skins. 

And, when you open old V2 AK skins on rust workshop, the magazine and body files are on the incorrect tab.
