### ISSUE TITLE
Normal maps don't display correct.

### ISSUE THREAD

**Issue by Tatten** [Facepunch/RustWorkshop#6]
Something with the normal maps doesn't seem to be working properly. 

Starting a new workshop item, saving the normal map and then selecting to use that saved map as the normal causes problems with a shift and very visible seams. 
http://i.imgur.com/aqsaRA9.png

Not sure if its related - Tint of newly saved normals are far different from those saved from the unity RustSDK.
http://i.imgur.com/5tlhZDw.png

**Comment by garrynewman** [comment]
Should be fixed in an hour

**Comment by Tatten** [comment]
Thank you so very much sir! 
Love the new Rust workshop, being able to see my skins in game rendering/lighting is excellent.
