### ISSUE TITLE
Bolt Rifle skins are too blurry

### ISSUE THREAD

**Issue by zufick** [Facepunch/RustWorkshop#60]
Can you reduce the compression of Bolt Rifle skins when uploading?
![pic](https://cloud.githubusercontent.com/assets/19573220/20785755/ac085de4-b7c3-11e6-9c84-3af95cec40d2.jpg)

**Comment by garrynewman** [comment]
Should be fixes on staging now

**Comment by zufick** [comment]
Yeah, it's fixed! Thx
