### ISSUE TITLE
Is it ok to add graffiti or words to add decoration on items?

### ISSUE THREAD

**Issue by elfideorubio** [Facepunch/RustWorkshop#61]
Hey Garry we worked really hard on this texture and we don't know if it could get accepted since it has some words in it 

http://steamcommunity.com/sharedfiles/filedetails/?id=809638761

please let us know if there is something to be fix here.

**Comment by garrynewman** [comment]
I think that item is more attractive for addtion without the words. The thing to keep in mind with doors is that there might be multiple doors, so to have 3 doors in a row with "no escape" scratched in them would be odd.

**Comment by elfideorubio** [comment]
yeah I see your point there, ok we will try to add a different detail for that part. I wanted to take the opportunity to say thanks for acepting the Unknown territory skin, It meant a lot to us since we dream of some day getting in the industry.

**Comment by garrynewman** [comment]
👍

**Comment by elfideorubio** [comment]
ok here's the version 2.0 hope you like it 

http://steamcommunity.com/sharedfiles/filedetails/?id=809638761
