### ISSUE TITLE
This new voting system on front page is kinda broken

### ISSUE THREAD

**Issue by Vazul267** [Facepunch/RustWorkshop#62]
I mean look at any item now, and you will see like hundreds of upvotes on them.  
People can just spam the living shit out of the voting window on front page.
Why is this bad you would ask!?
Well it makes the ratings not relevant.

Can you tell me Garry if this is what you wanted or something else?

**Comment by garrynewman** [comment]
How many people do you think are spamming

**Comment by Vazul267** [comment]
Why do you have to ask such a hard questions.
But anyway you are right.
Thanks for the answer.
