### ISSUE TITLE
Flow 'Likes"

### ISSUE THREAD

**Issue by bokatau** [Facepunch/RustWorkshop#63]
I and many other works, as I see, got a strange flow likes

![default](https://cloud.githubusercontent.com/assets/23529584/20814754/0d5a0238-b82c-11e6-910b-131285995677.JPG)

it grows in 1 for a second or thereabouts
But in Steam item not visited so often

![1111](https://cloud.githubusercontent.com/assets/23529584/20814783/3531b2ce-b82c-11e6-8693-044c3ce55df0.JPG)

They became more while I was writing this

![222222](https://cloud.githubusercontent.com/assets/23529584/20814830/59883f1c-b82c-11e6-9ea4-d6345f88e6ef.JPG)

If are living people after the upgrade and adding of voting in the game - no problem
But then there are too many, strange.

30 sec later...

![33333333](https://cloud.githubusercontent.com/assets/23529584/20814930/bf58c26c-b82c-11e6-8a05-c0ca1942f2f5.JPG)

Did you enter any restrictions on the evaluation of the game?
I can put autoclicker the vote and go to sleep?

**Comment by raycohaex** [comment]
You've adressed this like 3 times already...

![giphy 1](https://cloud.githubusercontent.com/assets/11200658/20815240/859c2fb4-b81d-11e6-8605-7906115db08f.gif)

**Comment by bokatau** [comment]
@DutchAllians ???

**Comment by raycohaex** [comment]
Issiue 51 and issiue 46 you also talked about the votes im pretty sure. But it's steam related and rust related
as you see steam can act up for me too sometimes
![image](https://cloud.githubusercontent.com/assets/11200658/20815456/24bc4f34-b81e-11e6-81ca-793bddc3cee3.png)
