### ISSUE TITLE
Workshop Spammers

### ISSUE THREAD

**Issue by Vazul267** [Facepunch/RustWorkshop#64]
Just looked on workshop to see some cool new items.
Got pages of spammers instead.
I tried to gather all I could. Here they are:

http://steamcommunity.com/profiles/76561198031511199/myworkshopfiles/?p=1
http://steamcommunity.com/id/-SOLLY-/myworkshopfiles/
http://steamcommunity.com/profiles/76561198169980578/myworkshopfiles/
http://steamcommunity.com/profiles/76561197989878099/myworkshopfiles/?appid=252490&p=1
http://steamcommunity.com/profiles/76561198079282902/myworkshopfiles/?appid=252490
http://steamcommunity.com/profiles/76561198253200306/myworkshopfiles/?appid=252490
http://steamcommunity.com/id/pixxyboy/myworkshopfiles/?appid=252490&p=2
http://steamcommunity.com/id/aSaHi_HAL9000/myworkshopfiles/?appid=252490
http://steamcommunity.com/id/emilkaenotik/myworkshopfiles/?appid=252490
http://steamcommunity.com/profiles/76561198037564558/myworkshopfiles/?appid=252490
http://steamcommunity.com/id/Xbeatzprodz/myworkshopfiles/?appid=252490
http://steamcommunity.com/profiles/76561198160033150/myworkshopfiles/?appid=252490

**Comment by Vazul267** [comment]
http://steamcommunity.com/id/-SOLLY-/myworkshopfiles/

**Comment by Vazul267** [comment]
http://steamcommunity.com/profiles/76561198169980578/myworkshopfiles/

**Comment by Vazul267** [comment]
http://steamcommunity.com/profiles/76561198079282902/myworkshopfiles/?appid=252490

**Comment by Vazul267** [comment]
http://steamcommunity.com/profiles/76561198253200306/myworkshopfiles/?appid=252490

**Comment by garrynewman** [comment]
This is what the REPORT button is for
