### ISSUE TITLE
Rocket Launcher Preview Image

### ISSUE THREAD

**Issue by Vazul267** [Facepunch/RustWorkshop#65]
It seems like the lighting is in bad position, because the image is dark and doesn't show the texture.

**Comment by bokatau** [comment]
I think its you Oclusion / Gloss / Fuzz layer problem
I create a random rocket launcher and fine see texture in preview :)

**Comment by Vazul267** [comment]
You cant really see anything out of this:
http://steamcommunity.com/sharedfiles/filedetails/?id=812737524&searchtext=

You only see lighting on the left side of it, and the rest is dark.

**Comment by Vazul267** [comment]
Thank you for the fix, it looks better now.
