### ISSUE TITLE
Authors feedback about new vote system

### ISSUE THREAD

**Issue by bokatau** [Facepunch/RustWorkshop#66]
Dear developers.

What I found for the next patch, saddened me.

![2016-12-05 16 00 15](https://cloud.githubusercontent.com/assets/23529584/20885892/4f334784-bb04-11e6-8c47-e9dbb355da26.png)

Current voting system is good, this system is worth to continue to develop, for example, make it so that the user would be asked to 3 items of the same category, for example 3 hats or 3 ak47, not random different things. Thus this system would be even better. You just have to watch where more likes.
There is also a defect - 2-3 dislike of haters can change your performance in percentage terms is very strong, because they are very few. But if you do not look at percentage, and look at the number - the system works well.

**Why the future voting system is bad**

This simplifies life haters. You can simply install autoclicker program and go to sleep.
If so you really have decided that this system is better - it is necessary to make a **random position** of the voting buttons.

**Comment by garrynewman** [comment]
Your arguments against the new system aren't persuading me.

**Comment by bokatau** [comment]
Any system in to varying degrees will produce specific results, the system can not "does not work" but what you plan - less successful than what we have now. I'm just saying the results will be dirtier and blurred.
