### ISSUE TITLE
Link to skin profile

### ISSUE THREAD

**Issue by bokatau** [Facepunch/RustWorkshop#67]
Dear developers
Perhaps, should add a link to the profile of the skin?

![2016-12-05 16 00 15](https://cloud.githubusercontent.com/assets/23529584/20887792/2b7a82ae-bb0d-11e6-9e0b-540a024f64ed.png)

Often, the skin may be interested in a person and he wants to see more **screenshots** and add it to **favorites** or write a **comment**. Often **one preview is not enough**, and manually find the one thing that you liked - almost impossible.

**Comment by garrynewman** [comment]
You should be able to click on it to view the preview

**Comment by bokatau** [comment]
Players should be able to click on this button to view the WorkShop page with this item
