### ISSUE TITLE
Open access to the texture skins

### ISSUE THREAD

**Issue by 0zki** [Facepunch/RustWorkshop#68]
@garrynewman Hey. I have a question. You know that everyone can view and download the texture of the skin of another person without any problems. If you do not see the problem, it's good. I just wanted to know whether you know about it.
![screenshot_2](https://cloud.githubusercontent.com/assets/24391275/20894174/fe2a0704-bb46-11e6-8fb7-f68343beeccb.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/24391275/20894399/d5ecf7be-bb47-11e6-8231-f9bdfe84a28d.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/24391275/20894517/5e0d487e-bb48-11e6-8e1e-8bbd45364f38.png)
![screenshot_5](https://cloud.githubusercontent.com/assets/24391275/20894833/8ab205e4-bb49-11e6-85e0-a12aefb92ff3.png)
![screenshot_7](https://cloud.githubusercontent.com/assets/24391275/20895037/633d6c28-bb4a-11e6-898b-6d03cbbb42a0.png)

**Comment by garrynewman** [comment]
Yeah we know, we don't consider it a problem.
