### ISSUE TITLE
wooden storage box texture is not working properly

### ISSUE THREAD

**Issue by elfideorubio** [Facepunch/RustWorkshop#7]
I tried to design something for this little box, I discovered that every single piece of wood is divided from the island and not showing in order, I'll link a picture so that you can see better.

[https://gyazo.com/274c71b0e5e4e14ead282d24b86f699d](url)

Another issue I came across is despite applying the texture clompletely on top of it I will get these gaps and I don't know why 

[https://gyazo.com/e2564e4e68edc7d59b7f32b18693bbbe](url)
[https://gyazo.com/64a793911700b2fa9cecfb7e0c4106c6](url)

**Comment by DevinWatson** [comment]
It's just how they've mapped the texture to the model. Once they update with the ability to export the model file you'll be able paint directly on the model in Photoshop or w/e.
