### ISSUE TITLE
AK47 Base Texture Bug

### ISSUE THREAD

**Issue by Vazul267** [Facepunch/RustWorkshop#71]
As you can see on the picture, the grip is using the texture of the trigger a bit.
Probably because the trigger and grip texture is too close.
Whenever I try to edit that part, it looks like that both of these parts are using the same texture.
http://i.imgur.com/uLydYXb.jpg
http://i.imgur.com/WtQ9KI1.png

**Comment by garrynewman** [comment]
This should be fixed on the staging branch now

**Comment by Vazul267** [comment]
There is also a few on the magazine and the barrel. (white lines)
The base texture is not wide enough, or the model is using the texture incorrectly.
Thank you for the fix though.
