### ISSUE TITLE
Can't find Original Textures.

### ISSUE THREAD

**Issue by AlphaLionAL** [Facepunch/RustWorkshop#72]
Dear Reader(s).

I'm very interested to contribute my imagination to the Workshop.
But i can't seem to find the original textures of the 'Miner's hat' .  (or any hat in that case)
I like to skin over the original and i have no clue if that's possible.

(Maybe i'm just dumb and i can't find it)

Kind Regards
Jordy

**Comment by AlphaLionAL** [comment]
And with textures i meant the Entire Diffuse map. ETC ( All in original standards!)

**Comment by garrynewman** [comment]
There's a download button on the left.

https://github.com/Facepunch/RustWorkshop/wiki/Creating-a-skin

**Comment by AlphaLionAL** [comment]
Yes i was dumb haha.

Appreciate the fast response and keep up the good work!
