### ISSUE TITLE
Strange selection of in-game voting

### ISSUE THREAD

**Issue by bokatau** [Facepunch/RustWorkshop#73]
Dear Developers!

I watch some of the problems with getting into the game menu voting.
I have absolutely strangely shown things that I was doing long ago, but does not have views on the things that I've done 2-3 days ago.

For example, here are the things are still shown, one of them has scored 8,400 likes for 6 days !!!
http://steamcommunity.com/sharedfiles/filedetails/?id=809874492 (add 1 dec)
http://steamcommunity.com/sharedfiles/filedetails/?id=810526943 (add 2 dec)
I watched from the menu made things even later than these.

But these things are more important to me - do not appear in the game. I do not get to them views since they disappeared from the "New". They were made very recently! They die early :)

http://steamcommunity.com/sharedfiles/filedetails/?id=811902976 (add 4 dec)
http://steamcommunity.com/sharedfiles/filedetails/?id=811751345 (add 4 dec)

These things do not have much dislike (96-97% like) or something that would have prevented them get to the menu. But they did not get there.

I do not need any feedback on this issue, I just want to call your attention to this.

**Comment by garrynewman** [comment]
This will be changed in the next update
