### ISSUE TITLE
Thumbnail problem

### ISSUE THREAD

**Issue by Pornflakes0203** [Facepunch/RustWorkshop#74]
Hi, 

When I publish my item from the workshop my thumbnail does not look like everyone else... 
No blurry background and the item is not showed really well... 

I got a dark thumbnail with the publishing menu on the background... 

Same problem every time with any item. 

Any help ? 

![previewfile_812366327](https://cloud.githubusercontent.com/assets/24444410/20991824/f0d1f1ac-bce0-11e6-931e-59aa70d5a900.png)

**Comment by garrynewman** [comment]
Oh wow - are you on the staging branch?

**Comment by Pornflakes0203** [comment]
Oh sorry about that i did not activate the staging branch!

Now everything seems to work!

Thank you!

2016-12-08 11:12 GMT+01:00 Garry Newman <notifications@github.com>:
