### ISSUE TITLE
Emission not working with Alpha-Cutoff

### ISSUE THREAD

**Issue by NennMichIltis** [Facepunch/RustWorkshop#75]
When I apply the Alpha-Cutoff and the Emission on the Metal Facemask stops working, and i use Both. :(

I have create a Bullethole in the Mask but when i use the Emission, i must push the Alpha Cutoff to the Left when i want see the Effect, but the Bullethole will be closed.

Here is a Video for example:
http://plays.tv/video/5848d5086b4030e879/fix

**Comment by kfhammond** [comment]
I'm having the same problem. Would love a fix for this.
