### ISSUE TITLE
Rustworkshop doesn't show the skins I did

### ISSUE THREAD

**Issue by soulfreak1** [Facepunch/RustWorkshop#78]
I have been doing a lot of skins on rust workshop and when i press to see recent skins or last skins they never appear, why is it that this happen?

**Comment by soulfreak1** [comment]
PD: The skins i did, already appear on my profile, they were already published

**Comment by Subza** [comment]
You need to finalize your revenue sharing, which can't be done unless you add your bank and tax information into your steam account.

**Comment by soulfreak1** [comment]
So I need to put my bank information yes or yes? thank you, now im going to get the numbers and all that stuffs!

**Comment by garrynewman** [comment]
Yeah you need to do all that
