### ISSUE TITLE
New preview images for the SAR and SMG

### ISSUE THREAD

**Issue by Vazul267** [Facepunch/RustWorkshop#80]
They focus on the stock, rather than on the body of the weapon.
I understand that you have to make it, that everything is seen on it.
Can you make them in the same position as the ak47?

**Comment by kfhammond** [comment]
I agree with this. I also think the bolt-side of the smg should be viewed in the thumbnail, as its the side you see first-person ingame

**Comment by garrynewman** [comment]
Done

**Comment by kfhammond** [comment]
Thanks Garry :)
