### ISSUE TITLE
Door skin icons

### ISSUE THREAD

**Issue by Kamiling** [Facepunch/RustWorkshop#81]
New door skins on workshop look like this.
Sheet Doors
![1](https://cloud.githubusercontent.com/assets/23229044/21071062/9e1c7fec-be73-11e6-9757-62b5048e0e53.jpg)
Armored Doors
![2](https://cloud.githubusercontent.com/assets/23229044/21071063/9e1cc10a-be73-11e6-8a5f-840e647ab7d5.jpg)
Wooden Doors
![3](https://cloud.githubusercontent.com/assets/23229044/21071064/9e2264ca-be73-11e6-9f04-723afd3d9db2.jpg)

**Comment by Vazul267** [comment]
Spooky.

**Comment by Kamiling** [comment]
Fixed a while ago... closed
