### ISSUE TITLE
Updating an item

### ISSUE THREAD

**Issue by Vazul267** [Facepunch/RustWorkshop#82]
I recently updated my item,  but I can't see the changes in game because the old files that the workshop downloaded are still there.
I tried deleting the previous folders that I downloaded when I first made it, but it doesn't download the new ones.
Can you explain this or work something out to fix it?

I'm talking about this item in particular if it helps: http://steamcommunity.com/sharedfiles/filedetails/?id=813572816

**Comment by garrynewman** [comment]
This happens, wait a couple of hours, restart Steam, then verify Rust's integrity - it should download the newer versions.
