### ISSUE TITLE
P250 wrong model

### ISSUE THREAD

**Issue by SKYCrap** [Facepunch/RustWorkshop#84]
Hello, just see these two screenshots:
This is workshop model (I guess wrong LOD)
![2057d6dc510f23e80901c4e575f0153e](https://cloud.githubusercontent.com/assets/24544265/21141504/5e661270-c15f-11e6-98eb-a98ed721e9cf.jpg)
And this is how it looks in-game
![-2](https://cloud.githubusercontent.com/assets/24544265/21141491/518a7b18-c15f-11e6-8bd8-660184bc85fb.png)
See the difference?

**Comment by zufick** [comment]
doesn't really matter

**Comment by raycohaex** [comment]
probaly depends on your graphic quality, workshop is on fantastic/ultra by default right?

**Comment by kfhammond** [comment]
yeah I was wondering where that spring went...

**Comment by raycohaex** [comment]
Oh where the spring went, its because of the LOD.

**Comment by garrynewman** [comment]
The one at the top is the worldmodel, the one at the bottom is the viewmodel.
