### ISSUE TITLE
REQUEST/QUESTION Could we get the oppertunity to make small placeables like the teddybear?

### ISSUE THREAD

**Issue by raycohaex** [Facepunch/RustWorkshop#87]
Hello, sorry if this is not very rust workshop- issiue related. 

I'm curious if we could get an oppertunity to make 3D props like the teddy bear, Ofcourse within a certain polycount and texture size limit, that is understandable. And only 3D props, so no guns or anything i really mean smaller placeables you could maybe find in trashpiles as little extra, or craft hem for 20 wood or something. Pretty much base decoration.

Best regards,

Rayco

**Comment by garrynewman** [comment]
I would like this, there's things we need to consider though.. 

* Will we need people to create LODs (or will they be that low poly that it wouldn't matter)
* Will servers need to load the objects for collision testing etc. Workshop items have metadata, so it's possible we could just include the bounds with the item name and description, so the server wouldn't actually need to download them.
* How are craft costs going to be decided

**Comment by raycohaex** [comment]
Creating LOD's, it requires a guideline for people. I'd be more than happy to create it, but there are dynamic LOD generation tools in the unity asset store, but i dont know if that is a viable option.

And maybe instead of crafting them, they should spawn around your base or just on trash piles, or getting a small box that is like a "Creative box" and you can pick one item from it that you wanna craft. See it like a material that is only used for one thing which is base decoration. This way people can't spam their base full of them (i think).

**Comment by raycohaex** [comment]
Base decoration box, could spawn on trashpiles or as secondary drop in barrels besides the primary drop. But it's just a suggestion, i hope more creators have idea's to put in too

![image](https://cloud.githubusercontent.com/assets/11200658/21260779/e3ca6de2-c387-11e6-9813-0cfdfa0da2ff.png)

**Comment by raycohaex** [comment]
This was the asset that i was talking about. https://www.assetstore.unity3d.com/en/#!/content/43652
But it uses Decimation>collapse to generate it so far it seems. I'm not sure if it would help you guys out that much. Otherwise the creators would have to create the LOD's. Personally I'm familair with doing so but I'm unsure how many people are besides that.

**Comment by elfideorubio** [comment]
I like the idea of making small furniture, I always find like there's a need to customize your base further, also Garry can we know what happend with the wall paper I really liked the concept at the time.

https://i1.wp.com/playrust.com/wp-content/uploads/2015/10/wallpapers_003.jpg?resize=797%2C557

is it still a thing?

**Comment by garrynewman** [comment]
IIRC we dropped the wallpaper idea because of performance issues, lack of batching capability. We might be able to pick that idea up again soon - which would lend itself quite nicely to workshop integration (or have the game end up looking like second life).

Problem with LOD generators from the asset store is that they're generally made to be run in the editor, so we probably couldn't ship them with the game itself.

**Comment by raycohaex** [comment]
Yea that's true, would it be possible to create a algorithm inside the rust workshop tool? maybe that is a little hard to impossible, i'm not an experienced programmed myself so i can't judge. 
But i think people who have knowledge on 3D modelling would be able to make or learn how to make LOD's fairly easy, lots of manuals online. Otherwise they have a hard time making the 3D models anyway.

**Comment by raycohaex** [comment]
Otherwise there are things i mananged to find online for creators. But LOD's have to be good otherwise they're kinda useless so it's a hard call. https://www.mixamo.com/decimator
https://developer.valvesoftware.com/wiki/LOD_Models

**Comment by raycohaex** [comment]
I can send you a example model and im willing to help you out with this, you can email me at:  raycoh1299@gmail.com or add me on steam http://steamcommunity.com/id/fredthedoggo/

**Comment by StabbyMcStabface** [comment]
Dutch and I were talking about this in chat before and both expressed how much we'd love to be able to add things like furniture and decor to make player homes feel more like home (and, thus, enhance the "endgame" as well as increase one's investment in one's base/home). I am but a simple texture artist so the 3-D realm is beyond me, but I was thinking that if FP were to make some neutral "unskinned" placeables that could be skinned as is or edited by 3D folk  without having to stick to too strict a design (but within the size parameters set by the basic model) it may make things easier to implement? These would literally be things like "Gray Square", "Gray Post", "Gray Chair", etc. No advanced modeling or anything, and the rest could be left up to slightly more advanced community contributors. This could still be maintained the same way as the existing workshop, the "crafting costs" could be pre-assigned to the "base model", and maybe even the LOD issue could be resolved by still making it something of a collaboration between FP's modeler and the community?

**Comment by Vazul267** [comment]
I love the idea of creating our own 3d item and, the skinnable base decoration idea aswell. But we all know that this is only going to happen when Rust leaves early access. Because let's say it, this is just cosmetic, and the team has higher priority things to do before doing these kinda stuff.

**Comment by Criisp** [comment]
I think it would be awesome to make little furniture items for the workshop. I think they wouldnt need their own colliders just for example a little lamp which you could place on a workbench or something. I would love to create some models for the workshop.

**Comment by xtabxtudios** [comment]
I would love to make 3D objects for Rust. Bases need more interesting objects in them to improve aesthetics. One simple solution would be to allow workshop authors to make the objects, then Facepunch chooses the materials cost and possible game effects, if any.

**Comment by kfhammond** [comment]
I'm also interested in making meshes for the game. It looks like we are going to need a TF2 "Goldstar" style import tool, one that checks LOD polycount limits and such. But I was wondering in the meantime, should we use the v2 uploader to get meshes on the workshop and gauge community interest?
