### ISSUE TITLE
[SOLVED] Crossbow different color metallic shine.

### ISSUE THREAD

**Issue by raycohaex** [Facepunch/RustWorkshop#88]
The crossbow only reflects a "metal" shine, and i can't get a gold-bronse shine to work. Is it metallic setup?

**Comment by raycohaex** [comment]
EDIT, solved. But the setup is a bit strange it's different from the other guns. and skinnables.

**Comment by raycohaex** [comment]
You can close this now, sorry. I figured i had FUZZ map enabled.

**Comment by Vazul267** [comment]
you can close it yourself as well.

**Comment by raycohaex** [comment]
how?

Op 18 dec. 2016 19:37 schreef "Vazul267" <notifications@github.com>:
