### ISSUE TITLE
Bolt rifle OBJ download, third person view model instead of first person

### ISSUE THREAD

**Issue by raycohaex** [Facepunch/RustWorkshop#89]
Downloading the bolt rifle from rust workshop provides you with a third person view model instead of the first person one.

**Comment by SuccessMoneySparkle** [comment]
Is it possible to upload a skin to workshop with an edited model? Or why can we get the model of an item from rust?

**Comment by kfhammond** [comment]
Bump. Downloaded bolt obj is worthless for 3D painting.
