### ISSUE TITLE
Red mark next to some of my items in workshop, just wondering what this means.

### ISSUE THREAD

**Issue by HermaphroditicAmobea** [Facepunch/RustWorkshop#9]

**Comment by DevinWatson** [comment]
That means they are the older version of workshop items. You will need to update the items to the latest version. You can do that by opening them in Rust, converting the .tga's to .png' and re-publishing your item.

**Comment by garrynewman** [comment]
There's a bug right now that means the tags aren't updating, so the red mark isn't going away. Will be fixed soon.

**Comment by garrynewman** [comment]
Forgot to ask - is this done?

**Comment by HermaphroditicAmobea** [comment]
Yes, thank you, the update fixed it.

**Comment by garrynewman** [comment]
<3
