### ISSUE TITLE
Is it possible to upload a skin to workshop with an edited model?

### ISSUE THREAD

**Issue by SuccessMoneySparkle** [Facepunch/RustWorkshop#91]
Is it possible to upload a skin to workshop with an edited model? Or why can we get the model of an item from rust? And if possible then how?

**Comment by raycohaex** [comment]
No right now that isn't possible (yet?). You can use transparancy on the diffuse to make things invisable though like people did with the ak.

**Comment by raycohaex** [comment]
take a look at this. https://github.com/Facepunch/RustWorkshop/issues/87

**Comment by raycohaex** [comment]
You can get the model from rust because some people (including me) prefer to texture skins in a 3D viewport if you take a look at substance painter. It's really useful to have the 3D mesh.

**Comment by SuccessMoneySparkle** [comment]
Thank you for making this clear :D

**Comment by raycohaex** [comment]
no problem

**Comment by C336** [comment]
I'd appreciate this if it were available as I accidentally spent a bunch of time modifying the bolty in Blender only to realise after I was done that while you can download .obj files from the workshop, you cannot upload them haha

**Comment by raycohaex** [comment]
I've adressed this in Issiue 87, but the only issiue with that would be LOD's for example :p
