### ISSUE TITLE
Linvisible Legs under Clothes

### ISSUE THREAD

**Issue by NennMichIltis** [Facepunch/RustWorkshop#95]
Hi Guys

I have create in the last 4 Hours a new Pants Skin (Damaged Survival-Pants) and i cant see my Legs under the Pants. I have create Shorts for Pants. Do u can fix it pls :S Its will be bad when u dont accept my Skin because invisible Legs :c

Picture: https://i.gyazo.com/7a0a85165faee88f6d9c5a5e073f4a68.jpg

My Skin:
http://steamcommunity.com/sharedfiles/filedetails/?id=835839888

**Comment by raycohaex** [comment]
It's because the underlaying geometry isn't actually seen normally. Facepunch probaly removed that part of the legs for optimization

**Comment by StabbyMcStabface** [comment]
Yeah, same thing happens with the shirts. Try cutting off the sleeves of the long t-shirt. You become the invisible man. ;)

**Comment by NennMichIltis** [comment]
Thats Sucks :(

**Comment by raycohaex** [comment]
I'd recommend putting bandage wraps around the "invisable part" with some blood, i'd defenitly buy that if it would get ingame ;)

**Comment by StabbyMcStabface** [comment]
LOL. Can't, Dutch. Anything you try and put there reverts back to the shape of the shirt ;p

However, you could leave some invisible showing and make him some sort of Rad Mutant ;)

**Comment by NennMichIltis** [comment]
Why Dutch?
