### ISSUE TITLE
Rustworkshop downloads LOD'd models instead of LOD0

### ISSUE THREAD

**Issue by raycohaex** [Facepunch/RustWorkshop#96]
Rustworkshop download button gives a wrong LOD, in substance painter i get LOD 2 or something probaly. Many parts are missing.

I've experienced this with: 
-Bolt rifle
-Waterpipe shotgun

as you see the metal shards here are missing for me
![image](https://cloud.githubusercontent.com/assets/11200658/21714979/1d36d586-d402-11e6-8bc6-85d366a27c61.png)

**Comment by garrynewman** [comment]
This isn't a lower LOD model, it just isn't the viewmodel. The viewmodel is much higher res than the world model - but might be less useful as an actual obj.

**Comment by raycohaex** [comment]
I currently grab the models from the old RUST SDK, i kinda need every bits of the mesh included on the UV map for substance painter. Because you paint directly on the mesh and that gets updated on the UV map

**Comment by garrynewman** [comment]
I just pushed an update which should download the obj models of the viewmodel - which should always be the highest quality. If you find that individual models are lower LODs after that, let me know.
