### ISSUE TITLE
Suggestion for skinables

### ISSUE THREAD

**Issue by raycohaex** [Facepunch/RustWorkshop#97]
First of all, there are some door skins. But how about double door skins, could our textures be applied for those too in a near future. Or rather, having the current single door skins for double door aswell?.

Secondly, could we maybe get a few more skinnables. Here are some suggestions.
- Wood (window) Shutters
- Metal horizontal embrasure
- Metal verticle embrasure
- Bota bag
- (bed?)
- water bucket
- (c4?)

Thanks for reading, 
keep up the good work

**Comment by raycohaex** [comment]
> Or rather, having the current single door skins for double door aswell?.

Because they share the same uv it might be better to use the current door skins

**Comment by StabbyMcStabface** [comment]
Bow! I've been dying to skin a standard bow. I know it's not the most glamorous item, but I could have a lot of fun with exotic woods, carvings, etc.

**Comment by C336** [comment]
I reckon if we can use it, we should be able to skin it. However I also cringe at that prospect when I think of all the camo and galaxy print spammers that inhabit the workshop these days. :c

**Comment by raycohaex** [comment]
They're still quite populair, it really depends on the player. Personally i have a big fetish for rusted skins or skins that have a story if you know  what i mean

**Comment by Krovv** [comment]
TC

**Comment by StabbyMcStabface** [comment]
Oh and what of the Salvaged Axe?!

**Comment by raycohaex** [comment]
`TC`
That might be a bit annoying in raids, imagine if the TC doesnt really look like one. but idk

**Comment by Kamiling** [comment]
The C4 and Bed can be nice

**Comment by StabbyMcStabface** [comment]
LOL. I can see it now. TC's skinned in stone/armor/sheet metal. "Where the hell is it?!!"
