### ISSUE TITLE
Please add hair to bald bear model.

### ISSUE THREAD

**Issue by anacel777** [Facepunch/RustWorkshop#99]
If you add hair.Please add hair to bald bear model.

https://i0.wp.com/files.facepunch.com/taylor/2017/01/BearFur.jpg

google search "the bald bear"
http://www.dailymail.co.uk/news/article-1225042/Germanys-bald-bears-Fur-disease-afflicts-Dolores-baffles-vets.html

**Comment by raycohaex** [comment]
Hey, i think this is more for rust workshop :p

**Comment by kfhammond** [comment]
^ Bear Skins?

**Comment by raycohaex** [comment]
Rust reddit* not workshop
